FROM rayproject/ray-llm:2.52.0-py311-cu128

# Install required system packages
USER root
RUN apt-get update && apt-get install -y git build-essential

# Copy the verl source code into the container
# Assuming this Dockerfile is run from the root of the verl repository
COPY --chown=ray:users . /opt/verl
USER ray

# Install verl and dependencies
WORKDIR /opt/verl
RUN MAX_JOBS=8 pip install -e .
RUN pip install vllm flash-attn

# Revert to default working directory
WORKDIR /home/ray