# Base image
FROM docker.io/rocm/megatron-lm:v25.9_gfx942
# FROM docker.io/rocm/megatron-lm:v25.10

# Specify the commit of Primus-Turbo when building: docker build --build-arg PRIMUS_TURBO_COMMIT=xxx .)
# ARG PRIMUS_TURBO_COMMIT
ENV AITER_ROCM_ARCH=gfx942
ENV HIP_ARCHITECTURES=gfx942
ENV PYTORCH_ROCM_ARCH=gfx942

# Install basic dependencies
RUN apt-get update && apt-get install --reinstall binutils -y && apt-get install numactl -y

# Clone and install the Primus-Turbo
# WORKDIR /opt
# RUN mkdir -p /opt && cd /opt && \
#     git clone https://github.com/AMD-AGI/Primus-Turbo.git && \
#     cd Primus-Turbo && \
#     git checkout ${PRIMUS_TURBO_COMMIT} && \
#     git submodule update --init --recursive && \
#     pip3 install -r requirements.txt && \
#     GPU_ARCHS="gfx942;gfx950" pip3 install --no-build-isolation .

RUN pip install ray && \
    pip install "numpy<2.0" && \
    pip install --upgrade "openai>=1.99.4"

WORKDIR /opt
RUN mkdir -p /opt && cd /opt && \
    git clone https://github.com/NVIDIA-NeMo/Megatron-Bridge.git && \
    cd Megatron-Bridge && \
    git checkout 9577b1280eaadd60b9d7b0ce6df09ac80e87e323 && \
    pip install -e . --no-deps

WORKDIR /opt
RUN mkdir -p /opt && cd /opt && \
    rm -rf aiter && pip uninstall -y aiter && \
    git clone https://github.com/ROCm/aiter.git && \
    cd aiter && \
    git checkout v0.1.7.post2 && \
    git submodule update --init --recursive && \
    python3 setup.py develop

WORKDIR /opt
ENV NVTE_FRAMEWORK=pytorch
ENV NVTE_ROCM_ARCH=gfx942
ENV NVTE_USE_HIPBLASLT=1
ENV NVTE_USE_ROCM=1
ENV CMAKE_PREFIX_PATH="/opt/rocm:/opt/rocm/hip:/usr/local:/usr"
RUN mkdir -p /opt && cd /opt && \
    rm -rf TransformerEngine && pip uninstall -y transformer_engine && \
    git clone https://github.com/ROCm/TransformerEngine.git && \
    cd TransformerEngine && \
    git checkout 90c04bcdc3c109505b318f40a39680263af55edf && \
    git submodule update --init --recursive && \
    pip install --no-build-isolation .

WORKDIR /opt
RUN mkdir -p /opt && cd /opt && \
    git clone https://github.com/NVIDIA/Megatron-LM.git && \
    cd Megatron-LM && \
    git checkout 847781764fe468c90caec16309deded245c1022c && \
    pip install -e . --no-deps

WORKDIR /opt
COPY ./patch_vllm.diff /opt/
RUN mkdir -p /opt && cd /opt && \
    git clone https://github.com/vllm-project/vllm.git && \
    cd vllm && mv ../patch_vllm.diff . && \
    git checkout 803e3f3f688677701a616d692125e181116d6b69 && \
    git apply patch_vllm.diff && \
    python3 -m pip install -r requirements/rocm.txt && \
    python3 setup.py clean --all && \
    ln -sf /opt/rocm/lib/libamdhip64.so /usr/lib/libamdhip64.so && \
    VLLM_TARGET_DEVICE=rocm ROCM_PATH=/opt/rocm/ VLLM_GPU_LANG=HIP MAX_JOBS=$(nproc) python3 setup.py bdist_wheel --dist-dir=dist && \
    pip install dist/*whl

WORKDIR /opt
RUN mkdir -p /opt && cd /opt && \
    git clone https://github.com/volcengine/verl.git && \
    cd verl && \
    git checkout 74f322453634c07bd9cb2d67533d68e42eb37710 && \
    pip install -e .

RUN pip install git+https://github.com/ISEEKYAN/mbridge.git --no-deps

# Set the default working directory
WORKDIR /opt

# check the installed Primus-Turbo package
# RUN python3 -m pip show primus-turbo || true