import re


# 模式1: "Answer: C", "The answer is C", "Option: C"
# 模式2: "(C)" 或 "C)" 或 "(C"
# 模式3: "C.", "C!", "C?" 或行首/行尾的单独字母
# 模式4: 行内明确标记的最终答案（如 "Final answer: C"）
patterns = [
    r'(?:answer|option)[:=\s]+([A-E])',
    r'\(?([A-E])\)?',
    r'(?:^|\s)([A-E])(?:\)|\.|$)',
    r'final answer[:=\s]+([A-E])'
]

def extract_option_letter(text: str, valid_options: str = 'ABCDE') -> str:
    """Extract option letter (A-E) from model output."""
    if not text:
        return ""
    
    text = text.strip().upper()
    
    # 直接匹配单个字母
    if len(text) == 1 and text in valid_options:
        return text
    
    # 多行取最后一行
    lines = text.split('\n')

    for line in reversed(lines):
        line = line.strip()
        if not line:
            continue
            
        line = line.upper()

        for pattern in patterns:
            match = re.search(pattern, line, re.IGNORECASE)
            if match:
                candidate = match.group(1).upper()
                if candidate in valid_options:
                    return candidate
            
        if line:
            break
        
    return ""

def extract_flexible(text: str, valid_options: str = 'ABCDE'):
    if not text:
        return ""
    
    text = text.strip().upper()

    for pattern in patterns:
        matches = re.findall(pattern, text)
        if matches:
            # 返回最后一个匹配的选项（通常最后的提及是最终答案）
            candidate = matches[-1]
            if candidate in valid_options:
                return candidate
    
    return ""


def compute_score(solution_str, ground_truth, method="flexible", format_score=0.0, score=1.0):
    """    
    Args:
        solution_str: Text generated by the model.
        ground_truth: Correct choice (A-E).
        method: not used
        format_score: Score given if the solution mentions the correct choice somewhere.
        score: Score for a correct answer.

    Returns:
        float: score (1.0 for correct, 0.0 for incorrect, or format_score if specified).
    """

    assert method in ["strict", "flexible"]

    if not solution_str or not ground_truth:
        return 0.0
    
    # 确保ground_truth是大写字母
    gt_letter = str(ground_truth).strip().upper()
    
    # 提取预测的选项
    pred_letter = extract_option_letter(solution_str)
    if pred_letter == gt_letter:
        return score
    
    # 宽松检查：如果文本中包含 "Answer: X" 且X正确，给部分分（可选）
    if method == "flexible" and format_score > 0:
        pred_letter = extract_flexible(solution_str)
        if pred_letter == gt_letter:
            return format_score
    
    return 0.0