# Required when using verl.utils.omega_conf_to_dataclass to instantiate dataclass configs
_target_: verl.workers.config.DistillationTeacherModelConfig

task: null

model_path: null

inference:
  _target_: verl.workers.config.RolloutConfig
  name: ${oc.select:actor_rollout_ref.rollout.name}
  dtype: ${oc.select:actor_rollout_ref.rollout.dtype}
  gpu_memory_utilization: 0.5
  enforce_eager: true
  cudagraph_capture_sizes: null
  free_cache_engine: true
  data_parallel_size: 1
  expert_parallel_size: 1
  tensor_model_parallel_size: 2
  max_num_batched_tokens: 8192
  max_model_len: null
  max_num_seqs: 1024
  load_format: auto
  engine_kwargs: {}
  limit_images: null
  enable_chunked_prefill: true
  enable_prefix_caching: true
  disable_log_stats: true
  skip_tokenizer_init: false

  prompt_length: ${oc.select:actor_rollout_ref.rollout.prompt_length}
  response_length: ${oc.select:actor_rollout_ref.rollout.response_length}
  temperature: ${oc.select:actor_rollout_ref.rollout.temperature}
