#!/usr/bin/env bash
set -xeuo pipefail

export CUDA_DEVICE_MAX_CONNECTIONS=1
export VLLM_USE_V1=1
export VERL_USE_GPT_OSS=0
export WANDB_MODE=${WANDB_MODE:-online}
export WANDB_PROXY_URL=${WANDB_PROXY_URL:-'http://yuhaiqiang:%7Bs%23fwCGAdJTQnFyE@proxy.ops.qihoo.net:8000'}
export HTTP_PROXY=${HTTP_PROXY:-$WANDB_PROXY_URL}
export HTTPS_PROXY=${HTTPS_PROXY:-$WANDB_PROXY_URL}
export http_proxy=${http_proxy:-$WANDB_PROXY_URL}
export https_proxy=${https_proxy:-$WANDB_PROXY_URL}
export PYTHONPATH=/llm-align/liuchonghan/verl_lao:${PYTHONPATH:-}
export GLOO_SOCKET_IFNAME=${GLOO_SOCKET_IFNAME:-eth0}
export NCCL_SOCKET_IFNAME=${NCCL_SOCKET_IFNAME:-eth0}
export RAY_TMPDIR=/hbox2dir/ray_tmp

ENTRYPOINT=${ENTRYPOINT:-"-m verl.trainer.main_ppo"}
TRAIN_FILES=${TRAIN_FILES:-/llm-align/liuchonghan/all_data_merged_rlhf.json}
MODEL_ID=${MODEL_ID:-/llm-align/liuchonghan/Qwen3-8B}
PROJECT_NAME=${PROJECT_NAME:-rlvr_8b}
EXPERIMENT_NAME=${EXPERIMENT_NAME:-rlvr_8b_grpo_fsdp_single}
DEFAULT_LOCAL_DIR=${DEFAULT_LOCAL_DIR:-/llm-align/liuchonghan/checkpoints/${PROJECT_NAME}/${EXPERIMENT_NAME}}

NNODES=${NNODES:-4}
NODE_RANK=${NODE_RANK:-0}
MASTER_ADDR=${MASTER_ADDR:-10.178.170.212}
MASTER_PORT=${MASTER_PORT:-23457}
N_GPUS_PER_NODE=${N_GPUS_PER_NODE:-8}

FSDP_STRATEGY=${FSDP_STRATEGY:-fsdp2}
FSDP_SIZE=${FSDP_SIZE:-8}
ACTOR_OFFLOAD=${ACTOR_OFFLOAD:-False}
REF_OFFLOAD=${REF_OFFLOAD:-False}
CRITIC_OFFLOAD=${CRITIC_OFFLOAD:-False}

rollout_mode=${ROLLOUT_MODE:-async}
USE_FUSED_KERNELS=${USE_FUSED_KERNELS:-True}
RETURN_RAW_CHAT=${RETURN_RAW_CHAT:-True}
RAY_ADDRESS=${RAY_ADDRESS:-auto}
RAY_WORKING_DIR=${RAY_WORKING_DIR:-/llm-align/liuchonghan/verl_lao}
ACTOR_LR=${ACTOR_LR:-1e-6}
MIN_LR=${MIN_LR:-1e-7}
LR_DECAY_STYLE=${LR_DECAY_STYLE:-cosine}
GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.35}

python3 $ENTRYPOINT --config-path=/llm-align/liuchonghan/verl_lao/verl/trainer/config \
    --config-name='ppo_trainer.yaml' \
    algorithm.adv_estimator=grpo \
    data.train_files=$TRAIN_FILES \
    data.val_files=$TRAIN_FILES \
    data.val_max_samples=2048 \
    data.return_raw_chat=$RETURN_RAW_CHAT \
    data.train_batch_size=32 \
    data.max_prompt_length=1024 \
    data.max_response_length=1024 \
    data.filter_overlong_prompts=False \
    data.truncation='error' \
    actor_rollout_ref.model.path=$MODEL_ID \
    actor_rollout_ref.model.use_fused_kernels=$USE_FUSED_KERNELS \
    actor_rollout_ref.actor.strategy=$FSDP_STRATEGY \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=$FSDP_SIZE \
    actor_rollout_ref.actor.fsdp_config.param_offload=$ACTOR_OFFLOAD \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=$ACTOR_OFFLOAD \
    actor_rollout_ref.actor.optim.lr=$ACTOR_LR \
    +actor_rollout_ref.actor.optim.min_lr=$MIN_LR \
    +actor_rollout_ref.actor.optim.lr_decay_style=$LR_DECAY_STYLE \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode=$rollout_mode \
    actor_rollout_ref.rollout.gpu_memory_utilization=$GPU_MEMORY_UTILIZATION \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.max_num_batched_tokens=10384 \
    actor_rollout_ref.rollout.max_model_len=2048 \
    actor_rollout_ref.ref.fsdp_config.fsdp_size=$FSDP_SIZE \
    actor_rollout_ref.ref.fsdp_config.param_offload=$REF_OFFLOAD \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    critic.strategy=$FSDP_STRATEGY \
    critic.model.fsdp_config.fsdp_size=$FSDP_SIZE \
    critic.model.fsdp_config.param_offload=$CRITIC_OFFLOAD \
    critic.model.fsdp_config.optimizer_offload=$CRITIC_OFFLOAD \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.default_local_dir=$DEFAULT_LOCAL_DIR \
    trainer.val_before_train=True \
    trainer.n_gpus_per_node=$N_GPUS_PER_NODE \
    trainer.nnodes=$NNODES \
    trainer.save_freq=300 \
    trainer.test_freq=300 \
    trainer.total_epochs=5 \
    +ray_kwargs.ray_init._temp_dir=$RAY_TMPDIR \
    +ray_kwargs.ray_init.address=$RAY_ADDRESS \
    +ray_kwargs.ray_init.runtime_env.working_dir=$RAY_WORKING_DIR \
    +ray_kwargs.ray_init.runtime_env.env_vars.PYTHONPATH=$RAY_WORKING_DIR:${PYTHONPATH:-} \
    +ray_kwargs.ray_init.runtime_env.env_vars.MASTER_ADDR=$MASTER_ADDR \
    +ray_kwargs.ray_init.runtime_env.env_vars.MASTER_PORT=\"$MASTER_PORT\" \
    +ray_kwargs.ray_init.runtime_env.env_vars.NCCL_SOCKET_IFNAME=$NCCL_SOCKET_IFNAME \
    +ray_kwargs.ray_init.runtime_env.env_vars.GLOO_SOCKET_IFNAME=$GLOO_SOCKET_IFNAME \
    +ray_kwargs.ray_init.runtime_env.env_vars.WANDB_MODE=$WANDB_MODE \
    +ray_kwargs.ray_init.runtime_env.env_vars.WANDB_PROXY_URL=$WANDB_PROXY_URL \
    +ray_kwargs.ray_init.runtime_env.env_vars.HTTP_PROXY=$HTTP_PROXY \
    +ray_kwargs.ray_init.runtime_env.env_vars.HTTPS_PROXY=$HTTPS_PROXY \
    +ray_kwargs.ray_init.runtime_env.env_vars.http_proxy=$http_proxy \
    +ray_kwargs.ray_init.runtime_env.env_vars.https_proxy=$https_proxy \
    custom_reward_function.path=/llm-align/liuchonghan/verl_lao/recipes_custom/RLVR_ABCDE_dense/reward_function.py \
    custom_reward_function.name=char_count_reward_function
