# automodel ref config, inheriting from trainer/config/ref/ref.yaml
defaults:
  - ref

  # automodel engine config
  - ../engine@automodel: automodel

  # load the reference default config, then apply the fields in the current yaml
  - _self_

_target_: verl.workers.config.AutomodelActorConfig

strategy: automodel

automodel:
  tp_size: ${oc.select:actor_rollout_ref.actor.automodel.tp_size,1}
  cp_size: ${oc.select:actor_rollout_ref.actor.automodel.cp_size,1}
  ep_size: ${oc.select:actor_rollout_ref.actor.automodel.ep_size,1}
  dp_replicate_size: ${oc.select:actor_rollout_ref.actor.automodel.dp_replicate_size,1}
  distributed_strategy: ${oc.select:actor_rollout_ref.actor.automodel.distributed_strategy,fsdp2}
  attn_implementation: ${oc.select:actor_rollout_ref.actor.automodel.attn_implementation,sdpa}
  model_dtype: ${oc.select:actor_rollout_ref.actor.automodel.model_dtype,bf16}
  backend_config: ${oc.select:actor_rollout_ref.actor.automodel.backend_config,null}
  forward_only: True
