hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - ppo_trainer
  - _self_

algorithm:
  adv_estimator: maxrl
  norm_adv_by_std_in_grpo: false
  filter_groups:
    enable: true
    metric: acc
    min: 0.0
    max: 0.8
  
  rollout_correction:
    bypass_mode: true

data:
  apply_chat_template_kwargs:
    enable_thinking: false
  train_files: ./data/apertus_demo_rl/train.parquet
  val_files: ./data/apertus_demo_rl/val.parquet
  train_batch_size: 0
  gen_batch_size: 1
  max_prompt_length: 2048
  max_response_length: 8192
  truncation: left

async_training:
  staleness_threshold: 0.2
  trigger_parameter_sync_step: 1
  require_batches: 2  # NOTE: train_batch_size = require_batches * ppo_mini_batch_size
  partial_rollout: true
  use_rollout_log_probs: true
  compute_prox_log_prob: false
  use_trainer_do_validate: false
  checkpoint_engine:
    enable: false
    device_buffer_size_M: 4096
    overlap_broadcast_and_consume: false

rollout:
  nnodes: 1
  n_gpus_per_node: 2
  total_rollout_steps: 180000
  total_epochs: ${trainer.total_epochs}

actor_rollout_ref:
  hybrid_engine: false
  nccl_timeout: 1800
  checkpoint_engine: ${oc.select:async_training.checkpoint_engine,null}

  model:
    path: swiss-ai/Apertus-8B-Instruct-2509
    use_remove_padding: true
    enable_gradient_checkpointing: true
    use_shm: false
    override_config:
      attn_implementation: flash_attention_3

  actor:
    use_rollout_log_probs: ${oc.select:async_training.use_rollout_log_probs,true}
    ppo_mini_batch_size: 128  # NOTE: train_batch_size = require_batches * ppo_mini_batch_size
    use_dynamic_bsz: true
    ppo_max_token_len_per_gpu: 32768

    optim:
      optimizer: _AdamW
      lr: 1e-6
      weight_decay: 0.01
      clip_grad: 1.0
      optimizer_impl: torchao.optim
      override_optimizer_config:
        bf16_stochastic_round: true
    strategy: fsdp2
    fsdp_config:
      strategy: fsdp2
      param_offload: false
      optimizer_offload: false
      entropy_from_logits_with_chunking: ${oc.select:actor_rollout_ref.actor.entropy_from_logits_with_chunking,false}
      entropy_checkpointing: ${oc.select:actor_rollout_ref.actor.entropy_checkpointing,false}
      model_dtype: bf16
      mixed_precision:
        param_dtype: bf16
        reduce_dtype: bf16
        buffer_dtype: bf16
    clip_ratio_high: 0.28
    clip_ratio_low: 0.2
    use_kl_loss: false
    policy_loss:
      loss_mode: geo_mean
    loss_agg_mode: seq-mean-token-mean  # unused by geo_mean, set for consistency
    shuffle: true

  rollout:
    nnodes: ${rollout.nnodes}
    n_gpus_per_node: ${rollout.n_gpus_per_node}
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 32768
    max_num_batched_tokens: 8192
    max_num_seqs: 256
    gpu_memory_utilization: 0.8
    tensor_model_parallel_size: 1
    n: 8
    name: sglang
    mode: async
    calculate_log_probs: true
    checkpoint_engine:
      backend: nccl
    dtype: bfloat16
    multi_stage_wake_up: true
    free_cache_engine: true
    enforce_eager: false
    load_format: safetensors
    val_kwargs:
      do_sample: True
      n: 4
      top_p: 0.95
      temperature: 0.7

critic:
  strategy: fsdp2
  checkpoint:
    save_contents: []

trainer:
  # NOTE: as we have DAPO group filtering, completing one epoch
  # may not correspond to going through the entire dataset.
  total_epochs: 2
  total_training_steps: 689 # 176213 samples / 256 effective async batch size = ~689
  save_freq: 20
  test_freq: 10
  max_actor_ckpt_to_keep: 10
  max_critic_ckpt_to_keep: null
  project_name: apertus-rl-tests
  experiment_name: GRPO
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 2
  log_val_generations: 5
  val_before_train: false # TODO: modify
  default_local_dir: ./outputs/${trainer.project_name}/${trainer.experiment_name}
  validation_data_dir: ${trainer.default_local_dir}/validation/

ray_kwargs:
  ray_init:
    num_cpus: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,null}}
  timeline_json_file: null
